version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./build/php/Dockerfile
    container_name: casper_app
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/html
      - ./build/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9004:9004"
    networks:
      - laravel
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casper
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
